---
title: "Welcome to the R Course!"

output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


---

### This is the course website for **BIOS 967: Intro to R for Biologists**. I will post course modules here each week.

---

## Updates

* 9/12/19: I have now uploaded [Assignment 3](pdfs/Assignment3.pdf). This assignment is to use the data that you have uploaded to make a figure for an analysis you want to conduct with the data. 

* 9/12/19: Starting next week, I will be holding office hours on **Tuesday/Friday 10-11am ** at my office, 410B Manter Hall. There will be a few days I know I will not be able to make it though: (e.g., September 27, October 8, October 18).

* 9/10/19: Today, we will be starting on plotting in R! On Thursday, we will be putting these lessons to practice and reproducing figures from [this publication (Bowden et al., 2016)](https://doi.org/10.1098/rsbl.2015.0574) using archived data. Please read this brief paper before class on Thursday. [Download the pdf here: Bowden et al. (2016).](pdfs/Bowden2016.pdf)

* 9/6/19: I have now uploaded an example for Assignment 2. The example folder is available (as .zip file) [here](data/Assignment2_example.zip).

* 9/5/19: I have now uploaded [Assignment 2](pdfs/Assignment2.pdf). In this assignment, you will create and upload a project folder that includes the data file (.csv), .rproj file, and a .R script file. 

* 9/5/19: In the "Formatting Data" module, I borrow heavily from the ["Data Organization in Spreadsheets for Ecologists"](https://datacarpentry.org/spreadsheet-ecology-lesson/) lesson from [datacarpentry.org](datacarpentry.org). I encourage you to go take a look at the lesson. 

* 8/29/19: **Assignment 1** Here is the [assignment file](pdfs/Assignment1.pdf) and an [example assignment folder](data/Assignment1_example.zip). This file includes a sample dataset and a sample readme file.


* 08/27/19: **Week 1!** Welcome to the course! First, we will go through some intros and course mechanics. Then, we will plan to get through Modules 1 and 2 (See ["Modules" page](modules.html)), which will get us up and running with R. There will be an assignment posted on Thursday, to be completed by Tuesday next week. 



---

##Quick Links:

- ####[Course Cryptpad page](https://cryptpad.fr/code/#/2/code/edit/2HTA5OzxqpIDW9RvkboNR445/){target="_blank"}

- ####Syllabus: click on the "Syllabus" tab above, or [download pdf version](pdfs/syllabus.pdf).
