---
title: "Learning Modules"
author: "Dai Shizuka"
date: "updated `r format(Sys.time(), '%m/%d/%y')` "
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

* ### 1. Getting Started

  + ### [Let's get started with R!](01_Intro.html)

  + ### [Types of Objects (vectors, strings, matrices, dataframes, lists)](02_ObjectTypes.html)

  + ### [Directories, Pathnames, and RStudio Projects](03_Rproject.html)
  
  + ### [Working with Data](04_Data.html)
  
  + ### [Setting up GitHub for your independent projects](05_GitHub.html)  

* ### Plotting in R:

    + ### [Basics of Plots](06_Plots_basics.html)
    
    + ### [Intro to ggplot2](07_ggplot_intro.html)


* ### Wrangling data in R:

    + ### [Data Wrangling with dplyr](09_dplyr.html)
    
    + ### [Parsing Dates and Text](10_text_parsing.html)
    
    
* ### Stats in R:

    + ### [Linear Models in R (including ANOVA, GLM)](08_Stats_LinearModels.html)
    

* ### Functions, Sampling, and Batch Processing

  + ### [Custom Functions (and if-else statements)](11_Functions.html)

  + ### [Apply Fuctions and Loops](12_Apply.html)
    
  + ### [Randomizations and Sampling From Distributions](13_RandomNumbers.html)

  + ### [Batch Processing (Example using Flack et al. 2014)](14_batch.html) 

* ### Mini-modules (in progress):
  
  + ### [Reshaping data with pivot functions](09.5_pivot.html)

* ### Reports

  + ### [Generating reports with RMarkdown](15_Rmarkdown.html)

* ### Extras
  + ### [What now? More resources for continuing to learn R](resources.html)

***

## Worked Examples: 

#### *These are lessons that use real or simulated data to demonstrate skills that are covered in the learning modules above.*


* #### [Worked Example: Simulating Population Growth](x_PopGrowth.html)

* #### [Worked Example: Wrangling World Bank Data](x_WorldBank.html)

* #### [Worked Example: Data wrangling with coot chick color data](x_CootDataWrangling.html)

* #### [Worked Example: Plotting the change of butterfly size under climate change](x_Bowden.html)

* #### [Worked Example: Plots and stats on effect of anthropogenic noise on crab physiology](x_Wale.html)

    