---
title: "BIOS 967: Intro to R for Biologists"

subtitle: "Syllabus, Fall 2019"

date: "updated `r format(Sys.time(), '%m/%d/%y')` "

output: pdf_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

***
###<u>Time/Location</u>  
* **T/Th 2-3:20pm @ 210 Brace Labs **  
  
###<u>Instructor</u>  
* **Dai Shizuka**
* **Office: 410B Manter Hall**
* **Email: dshizuka2'at'unl.edu** 

###<u>Course Website</u>  
####Course materials will be posted at the course blog: [https://dshizuka.github.io/RCourse/](https://dshizuka.github.io/RCourse/)####  
  
###<u>Course Goals</u>  
* Get over the hump in learning the R programming language and become proficient in using R for a variety of purposes, including wrangling data, generating plots, conducting analyses, and generating reports.
* Learn to conduct **reproducible research** and to reproduce research of others
* Make progress on own research by tackling complex tasks with R



###<u>Required Materials</u>
* **Laptop computer**: You will need access to a laptop computer that you can reliably use during class each week.
* **Installed programs**: see the ** Before the Course ** section below  

###<u>How the Course Works</u>

* Class sessions will consist of live-coding sessions led by the instructor, as well as individual and group exercises.

* Each class session will have an acommpanying web module that provides details and codes. These are designed to be guides that will help you retain the information in the future. Compiled together, this will essentially be your textbook.

* Most weeks, we will start a task during the Thursday session, which will then turn into a homework assignment. Sometimes this will entail generating and submitting code scripts. Other times, it will require you to prepare data, look up literature, or other tasks.

* The last part of the semester will mostly be dedicated to conducting independent research projects.

###<u>Evaluation</u>  
Students will be evaluated based on 4 criteria. (1) Participation [25 points], (2) Take-home assignments [25 points], (2) Project proposal [15 points] (3) Write-up of independent project [35 points].

###<u>Independent Project</u>
You will spend several weeks during the course conducting independent projects. We will have regular class during this time, but I will be available to help you with your R codes. This is an opportunity for you to work on something new that will further your research goals. I will leave the format fairly open, but here are some suggestions:
(1)	Conduct new analyses of your own data
(2)	Re-create models and/or figures from a publication in your field (I recommend this approach—it really helps you understand concepts at a new level).
(3)	Conduct meta-analyses or re-analysis of publically available data. 

You will submit a brief plan (< 2 pages) of your project on During the 5th week of the course. However, you can start your project earlier than that. You will submit a write-up (~5 pages, double-spaced including figures) at the end of the course. 

###<u>Students with disabilities</u> 
Students with disabilities are encouraged to contact the instructor for a confidential discussion of their individual needs for academic accommodation. It is the policy of the University of Nebraska-Lincoln to provide flexible and individualized accommodation to students with documented disabilities that may affect their ability to fully participate in course activities or to meet course requirements. To receive accommodation services, students must be registered with the Services for Students with Disabilities (SSD) office, 132 Canfield Administration, 472-3787 voice or TTY.

***

\pagebreak

###<u>Tentative course schedule (subject to change!)</u>

* Week 1 (Aug 27, 29): Getting started with R

* Week 2 (Sept 3, 5): Data Wrangling

* Week 3 (Sept 10, 12): Plotting in Base R

* Week 4 (Sept 17, 19): Creating reports

* Week 5 (Sept 24, 26): Some simple statistics

* Week 6 (Oct 1, 3): Resampling, bootstrapping 

* Week 7 (Oct 8, 10): apply functions, loops, statements

* Week 8 (Oct 15, 17): Simulations, stochasticity, **Submit proposal for independent project**

* Week 9 (Oct 22, 24): *Fall Break (Tuesday)*; Write your own functions (Thursday)

* Week 10 (Oct 29, 31): Batch processing

* Week 11 (Nov 5, 7): Worked examples, independent projects

* Week 12 (Nov 12, 14): Worked examples, independent projects

* Week 13 (Nov 19, 21): Independent projects

* Week 14 (Nov 26, 28): *No class for Thanksgiving*

* Week 15 (Dec 3, 5): Independent projects

* Week 16 (Dec 10, 12): Independent projects; Submit final project on Thursday

***
###<u>Before the Course</u>  
Please do the following things before we meet for the first class.   

1. **Download and Install *R* **  
Go to [https://cran.r-project.org/](https://cran.r-project.org/) and follow directions for downloading and installing R. *Even if you already have R*, upgrade to the latest version. It will make things easier to have everyone on the same version.
2. **Download and Install *R Studio* **  
Go to [https://www.rstudio.com/products/rstudio/download/](https://www.rstudio.com/products/rstudio/download/) and download the **R Studio Desktop** installer. Follow directions to install the program.
3. **Bookmark the Course CryptPad**  
*CryptPad* is a super useful way to follow along with the codes in real time. We will use this site in class. I have created a course "pad". You should [bookmark this link in your favorite browser](https://cryptpad.fr/code/#/2/code/edit/2HTA5OzxqpIDW9RvkboNR445/){target="_blank"}
