---
title: "Modules"
author: "Dai Shizuka"
date: "updated `r format(Sys.time(), '%m/%d/%y')` "
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Learning Modules

* ### 1. Getting Started

  + ### [Let's get started with R!](Intro.html)

  + ### [Types of Objects (vectors, strings, matrices, dataframes, lists)](ObjectTypes.html)

  + ### [Workflow with RStudio Projects and GitHub](Workflow.html)

  + ### [Importing and Navigating Data](Data.html)

* ### Plotting in R:

    + ### [Basics of Plots](Plots_basics.html)
    
    + ### [Intro to ggplot2](ggplot_intro.html)

* ### Stats in R:

    + ### [Linear Models in R (including ANOVA, GLM)](Stats_LinearModels.html)

* ### Wrangling data in R:

    + ### [Data Wrangling with Tidyverse Packages](tidyverse.html)
    
    + ### [Parsing Dates and Text](text_parsing.html)

* ### Functions, Sampling, and Batch Processing

  + ### [Custom Functions (and if-else statements)](Functions.html)

  + ### [Apply Fuctions and Loops](Apply.html)
    
  + ### [Randomizations and Sampling From Distributions](RandomNumbers.html)

  + ### [Batch Processing (Example using Flack et al. 2014)](batch.html) 

* ### Reports

  + ### [Generating reports with RMarkdown](Rmarkdown.html)

* ### [What now? More resources for continuing to learn R](resources.html)

***

## Worked Examples:

#### [Worked Example: Simulating Population Growth](example_PopGrowth.html)

#### [Worked Example: Wrangling World Bank Data](Ex_WorldBank.html)

#### [Worked Example: Data wrangling with coot chick color data](Example_CootDataWrangling.html)

#### [Worked Example: Plotting the change of butterfly size under climate change](Ex1.Plot_Bowden.html)

#### [Worked Example: Plots and stats on effect of anthropogenic noise on crab physiology](E2_Wale.html)

    